name: Deploy

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .Net
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI
      run: dotnet workload install maui

    - name: Restore
      run: dotnet restore
      working-directory: ./flafel-app/Flafel.Presentation

    - name: Build Application
      run: dotnet build -c Release -f:net8.0-windows10.0.19041.0
      working-directory: ./flafel-app/Flafel.Presentation

    - name: Publish Application
      run: dotnet publish -c Release -f:net8.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true
      working-directory: ./flafel-app/Flafel.Presentation

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: ./flafel-app/Flafel.Presentation/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/**/*.msix